server:
  port: 0

spring:
  liquibase:
    change-log: classpath:/database/changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
